### ISSUE TITLE
Moving (not selecting)

### ISSUE THREAD

**Issue by harrysolovay** [mfussenegger/nvim-ts-hint-textobject#10]
Apologies if I'm asking about a feature that isn't yet implemented. I can't quite tell whether or not this is possible.

Currently I have the following mapping:

```lua
vim.api.nvim_set_keymap("n", "m", "<cmd>lua require('tsht').nodes()<CR>", opts)
```

I can successfully initiate the search:

<img width="468" alt="Screen Shot 2021-10-17 at 10 46 26 AM" src="https://user-images.githubusercontent.com/4893548/137632649-5dcf911a-739d-4a93-a905-9709668e6b9e.png">

And can successfully select a given node (in this case by pressing `a`):

<img width="465" alt="Screen Shot 2021-10-17 at 10 46 37 AM" src="https://user-images.githubusercontent.com/4893548/137632654-cdeb2e77-b59a-496d-904e-32d68c07c4ef.png">

But what if I just want to move my cursor to the node start / end? How might this be accomplished? Is this possible?

Thank you!

**Comment by mfussenegger** [comment]
It's currently not possible.

But it is something I may add - I was waiting a bit to see which direction hop.nvim would take. It now has an extension API and maybe I can combine the two in some way.

**Comment by harrysolovay** [comment]
That would be A W E S O M E . No pressure, but I'd quite enjoy that integration. Thank you for considering! & let me know if you'd like for me to close out this issue.

**Comment by shaksiper** [comment]
Any news about this feature?

**Comment by max397574** [comment]
@mfussenegger any news about this?
I don't know how hard this would be to implement but imo it would be really cool.
And afaict by issues and prs hop.nvim doesn't want this in core.
I would prefer having this here over having it in a hop.nvim extension so people (like me) would need to install hop.nvim only for this feature

**Comment by max397574** [comment]
okay I tested this out on a fork
it's quite simple to do

**Comment by danielo515** [comment]
> okay I tested this out on a fork it's quite simple to do

@max397574 can you share your fork?

**Comment by max397574** [comment]
https://github.com/max397574/nvim-treehopper

**Comment by mfussenegger** [comment]
Added a `move` function with https://github.com/mfussenegger/nvim-treehopper/pull/21

**Comment by max397574** [comment]
you could check out my fork to see how you can do it quite easily without hop

**Comment by mfussenegger** [comment]
> you could check out my fork to see how you can do it quite easily without hop

Thanks for the pointer, but I don't mind the hop dependency in this case
