### ISSUE TITLE
Recommend x instead of v mapping

### ISSUE THREAD

**Issue by jemag** [mfussenegger/nvim-ts-hint-textobject#16]
A lot of users will often use the "select" mode for snippets. The current recommendations will trigger in select mode: 
```vim
vnoremap <silent> m :lua require('tsht').nodes()<CR>
```
meaning someone writing "m" while filling their snippets, will have the plugin trigger.

I believe most users would probably prefer to use visual only:
```vim
xnoremap <silent> m :lua require('tsht').nodes()<CR>
```

**Comment by mfussenegger** [comment]
Sounds good to me, can you create a PR?
