### ISSUE TITLE
No parser for `typescriptreact` language (when treesitter parser name is different from filetype)

### ISSUE THREAD

**Issue by Gelio** [mfussenegger/nvim-ts-hint-textobject#17]
When trying to use `nvim-treehopper` in a `tsx` file, I get the following error:

```sh
E5108: Error executing lua ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for
 'typescriptreact' language, see :help treesitter-parsers
stack traceback:
        [C]: in function 'error'
        ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:25: in function 'require_language'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:39: in function '_create_parser'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:98: in function 'get_parser'
        ...nvim/site/pack/packer/start/nvim-treehopper/lua/tsht.lua:53: in function 'nodes'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

https://user-images.githubusercontent.com/889383/173181320-7471c0ca-3580-4f3c-9794-6a09d90acb45.mp4

This seems to be caused by the treesitter parser for the `typescriptreact` filetype being named `tsx`. `nvim-treehopper` tries to use the parser with the same name as the filetype, which is not the case for quite a few filetypes, as shown in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/32e364ea3c99aafcce2ce735fe091618f623d889/lua/nvim-treesitter/parsers.lua#L4-L21).

I have decided to report this issue separately from my attempt at solving it (#14), since the progress on that PR has stifled while the issue remains.

**Comment by mfussenegger** [comment]
See https://github.com/mfussenegger/nvim-treehopper/pull/30
