### ISSUE TITLE
This plugin should deserve more attention.

### ISSUE THREAD

**Issue by hackingcat** [mfussenegger/nvim-ts-hint-textobject#3]
I have been using your plugins such as ndap series plugins. These plugins have given me an excellent development experience and productivity.  This plugin provides a better experience than nvim-treesitter-textobjects, I have put this plugin into the wiki page of nvim-treesitter, and I think this plugin should be put into your github home page readme.md. Last but not least, thank you for your continuous contributions to the nvim plugin.

**Comment by mfussenegger** [comment]
I've added the plugin to the list. Thank you for the kind feedback.
