### ISSUE TITLE
Recommended keymaps feel unnecessarily complex

### ISSUE THREAD

**Issue by SirWrexes** [mfussenegger/nvim-ts-hint-textobject#38]
I was trying out the plugin and couldn't get it to work with either
```lua
local tsht = require('tsht')
vim.keymap.set("o", "<Space>", tsht.nodes)
vim.keymap.set("x", "<Space>", tsht.nodes, { noremap = true })
```
or
```lua
vim.cmd([[ omap     <silent> <Space> :<C-U>lua require('tsht').nodes()<Cr> ]])
vim.cmd([[ xnoremap <silent> <Space> :     lua require('tsht').nodes()<Cr> ]])
```

However, simply doing this works just fine:
```lua
vim.keymap.set('n', '<Space>', tsht.nodes, { noremap = true })
```

Which leaves me with the following questions:
What's the point of all this fuss about Visual/Select (`mapmode-x`) modes ?
By extension, why use Operator-pending (`mapmode-o`) ?
Finally, why all this ceremony while simply just calling `tsht.nodes()` in Normal _Just Works™_ ?

Side note: Despite years of daily (Neo)Vim and constant ricing of it, I never knew Operator-pending existed; or seen it in a config for that matter. This by itself could end up being very confusing to a lot of users, as it feels highly unconventional. :thinking:

**Comment by mfussenegger** [comment]
I don't see what's highly unconventional about operator pending mode. It's what powers functionality like `dw` or `cw`, which to me are vi basics. The operator keymap allows you to do things like `d<tsht-trigger>` to delete a node.

The visual mode mapping creates some kind symmetry for that. Similar to how `d<tsht-trigger>` will delete a node, `v<tsht-trigger>` will select a node. Granted, explicit visual mode trigger is a bit redundant in this case as you'd end up with a visual selection anyway, but I like the explicitness and that it allows to use a key that has a different function in normal mode.

And they're just recommendations anyway. Part of the vi culture is to customize things to your own preferences.

**Comment by SirWrexes** [comment]
> The operator keymap allows you to do things like `d<tsht-trigger>` to delete a node.  

![brainsplode like a revelation](https://media1.tenor.com/m/RBdP_ptrbFMAAAAd/neil-patrick-harris-mindblown.gif)
My bad then. I simply never saw a plugin that required this type of setup before, but you just opened my eyes to a whole new world of possibilities, thanks !

> The visual mode mapping creates some kind symmetry for that. Similar to how `d<tsht-trigger>` will delete a node, `v<tsht-trigger>` will select a node. Granted, explicit visual mode trigger is a bit redundant in this case as you'd end up with a visual selection anyway, but I like the explicitness and that it allows to use a key that has a different function in normal mode.

Right, I understand now. Though it's weird: It just doesn't work for me, like at all.
Tried setting it up in lua then vimscript.
Tried using `<Space>` then `m` (thinking _mabe_ `<Space>` is being weird).
Tried using `:<C-U> ...` then `<Cmd>...`.
It jumps to the end of the node, and nothing is selected. However, if I do `v:lua require 'tsht' .nodes()` manually it works as expected.
Any idea ?

Thank you for your time. :pray:
