### ISSUE TITLE
Feature request: Goto textobject with hints

### ISSUE THREAD

**Issue by IndianBoy42** [mfussenegger/nvim-ts-hint-textobject#7]
Im imagining essentially a mix of easymotion/hop but using treesitter to identify places to jump to. 

I don't know if this is necessarily the right place for this functionality, but i think it already has the infrastructure for displaying hints, and identifying relevant text objects from treesitter. 

How hard do you think adding this would be? I could give it a go trying to implement it

**Comment by mfussenegger** [comment]
Sounds a bit related to https://github.com/phaazon/hop.nvim/issues/116 & https://github.com/phaazon/hop.nvim/pull/123

I kinda want to wait to see where that goes - it might be possible to turn this plugin here into just another "source" of targets for hop.nvim.

**Comment by danielo515** [comment]
isn't this the same as #10?

**Comment by mfussenegger** [comment]
> isn't this the same as #10?

Yes, sounds like a duplicate of https://github.com/mfussenegger/nvim-treehopper/issues/10
