### ISSUE TITLE
 Column value outside range

### ISSUE THREAD

**Issue by pittcat** [mfussenegger/nvim-ts-hint-textobject#8]
https://asciinema.org/a/fJ6lGBL3z0bBhBuBJz3Igr3QV
The error only occurs before formatting the code.

**Comment by pittcat** [comment]
Error info:
```
E5108: Error executing lua ...e/pack/packer/start/nvim-ts-hint-textobject/lua/tsht.lua:108: Column value outside range
```
Is there a temporary solution for the error ?
@mfussenegger

**Comment by mfussenegger** [comment]
Could you paste the source so that I could reproduce it?

**Comment by pittcat** [comment]
You change reproduce it by the sample code:
```vim
for i in range(1, 4)
  echo "count is" i
endfor
```

**Comment by assawalhy** [comment]
I got the same issue

```
E5108: Error executing lua ...config/nvim/plugins/nvim-ts-hint-textobject/lua/tsht.lua:108: Column value outside
range
```

Here is the file that I used in this video: https://github.com/MuhammadSawalhy/my-config/blob/master/linux/.config/nvim/plugins.vim

https://user-images.githubusercontent.com/42011920/132737815-06e2e041-5a0d-4799-8f27-8defa84a8d98.mp4

**Comment by mfussenegger** [comment]
Could you try with https://github.com/mfussenegger/nvim-treehopper/pull/11 ?

**Comment by mfussenegger** [comment]
I assume this got fixed with https://github.com/mfussenegger/nvim-treehopper/pull/11
