### ISSUE TITLE
Feature Request: Quickly select.

### ISSUE THREAD

**Issue by pu-007** [mfussenegger/nvim-ts-hint-textobject#9]
Use one key to quickly select a node, like [wildfire.vim](https://github.com/gcmt/wildfire.vim).

**Comment by mfussenegger** [comment]
Isn't this already possible with https://github.com/nvim-treesitter/nvim-treesitter-textobjects ?

**Comment by pu-007** [comment]
> Isn't this already possible with https://github.com/nvim-treesitter/nvim-treesitter-textobjects ?

Oh, thanks.
